# Generated by Django 2.1.5 on 2019-02-11 09:31

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=256)),
                ('coverImage', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('gettingThere', models.TextField()),
                ('featured', models.BooleanField()),
                ('location', geoposition.fields.GeopositionField(max_length=42)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.Region'),
        ),
        migrations.AddField(
            model_name='place',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
