# Generated by Django 2.1.5 on 2019-04-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='name',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='place',
            name='gallery',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
