# Generated by Django 2.1.5 on 2019-04-11 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20190411_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='slug',
            new_name='name',
        ),
    ]
