# Generated by Django 2.1.5 on 2019-04-11 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20190411_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='name',
            new_name='slug',
        ),
    ]
