# Generated by Django 2.1.5 on 2019-04-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20190411_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
