# Generated by Django 2.1.5 on 2019-04-22 11:02

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('places', '0006_auto_20190411_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atrraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=256)),
                ('coverImage', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('gettingThere', models.TextField()),
                ('featured', models.BooleanField()),
                ('location', geoposition.fields.GeopositionField(max_length=42)),
                ('gallery', models.CharField(blank=True, max_length=256, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.Place')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
