# Generated by Django 2.1.5 on 2019-04-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_atrraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='name',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='atrraction',
            name='place',
        ),
        migrations.AddField(
            model_name='place',
            name='attractions',
            field=models.ManyToManyField(blank=True, to='places.Atrraction'),
        ),
    ]
