# Generated by Django 2.1.5 on 2019-04-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20190424_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='attraction',
        ),
        migrations.AlterField(
            model_name='atrraction',
            name='place',
            field=models.ManyToManyField(blank=True, to='places.Place'),
        ),
    ]
