# Generated by Django 2.1.5 on 2019-04-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_auto_20190424_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atrraction',
            name='tags',
        ),
    ]
