# Generated by Django 2.1.5 on 2019-04-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_remove_atrraction_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atrraction',
            new_name='Attraction',
        ),
    ]
