# Generated by Django 2.1.5 on 2019-05-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20190428_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='places.Type'),
        ),
    ]
