# Generated by Django 2.1.5 on 2019-05-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_auto_20190502_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='type',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
