# Generated by Django 2.1.5 on 2019-05-02 11:23

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0014_auto_20190502_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=256)),
                ('coverImage', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('gettingThere', models.TextField()),
                ('featured', models.BooleanField()),
                ('location', geoposition.fields.GeopositionField(max_length=42)),
                ('gallery', models.CharField(blank=True, max_length=256, null=True)),
                ('place', models.ManyToManyField(blank=True, to='places.Place')),
            ],
        ),
    ]
