# Generated by Django 2.1.5 on 2019-03-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='name',
            field=models.CharField(default='default', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
