# Generated by Django 2.1.5 on 2019-03-12 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_auto_20190306_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='experience_images/category_covers'),
        ),
        migrations.AddField(
            model_name='experience',
            name='date_booked',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='experience_images'),
        ),
    ]
