# Generated by Django 2.1.5 on 2019-03-13 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('experiences', '0004_auto_20190313_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 13, 18, 53, 35, 465707, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 13, 18, 53, 35, 465663, tzinfo=utc), null=True),
        ),
        migrations.RemoveField(
            model_name='experience',
            name='category',
        ),
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.ManyToManyField(blank=True, to='experiences.Category'),
        ),
        migrations.RemoveField(
            model_name='experience',
            name='location',
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.ManyToManyField(blank=True, to='places.Place'),
        ),
    ]
