# Generated by Django 2.1.5 on 2019-05-20 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0044_auto_20190502_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='gallery',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='itinerary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 20, 16, 0, 14, 699899, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 20, 16, 0, 14, 699868, tzinfo=utc), null=True),
        ),
    ]
