# Generated by Django 2.1.5 on 2019-05-20 18:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0017_auto_20190502_1239'),
        ('experiences', '0046_auto_20190520_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, unique=True)),
                ('content', models.TextField()),
                ('date_booked', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='experience_images')),
                ('price', models.IntegerField(default=0)),
                ('gallery', models.CharField(blank=True, max_length=256, null=True)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 20, 18, 21, 48, 146871, tzinfo=utc), null=True)),
                ('end_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 20, 18, 21, 48, 146906, tzinfo=utc), null=True)),
                ('itinerary', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(blank=True, related_name='experiences_trip_related', related_query_name='experiences_trips', to='experiences.Category')),
                ('location', models.ManyToManyField(blank=True, related_name='experiences_trip_related', related_query_name='experiences_trips', to='places.Place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='experience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='name',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='experience',
            name='gallery',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='itinerary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='experiences_experience_related', related_query_name='experiences_experiences', to='experiences.Category'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='experiences_experience_related', related_query_name='experiences_experiences', to='places.Place'),
        ),
    ]
