# Generated by Django 2.1.5 on 2019-05-20 21:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_auto_20190502_1239'),
        ('experiences', '0049_auto_20190520_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='attractions',
            field=models.ManyToManyField(blank=True, to='places.Attraction'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 20, 21, 52, 36, 110656, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 20, 21, 52, 36, 110619, tzinfo=utc), null=True),
        ),
    ]
