# Generated by Django 2.1.5 on 2019-05-20 22:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_auto_20190502_1239'),
        ('experiences', '0050_auto_20190520_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='attractions',
            field=models.ManyToManyField(blank=True, to='places.Attraction'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 20, 22, 40, 10, 726705, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 20, 22, 40, 10, 726668, tzinfo=utc), null=True),
        ),
    ]
