# Generated by Django 2.1.5 on 2019-05-21 12:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0051_auto_20190520_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='experience',
            name='slug',
            field=models.SlugField(default='null', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 21, 12, 16, 18, 320217, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='slug',
            field=models.SlugField(default='null', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 21, 12, 16, 18, 320182, tzinfo=utc), null=True),
        ),
    ]
