# Generated by Django 2.1.5 on 2019-06-03 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0053_auto_20190521_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('image', models.ImageField(null=True, upload_to='experience_images/category_covers')),
            ],
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 3, 20, 52, 11, 445238, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 3, 20, 52, 11, 445199, tzinfo=utc), null=True),
        ),
    ]
