# Generated by Django 2.1.5 on 2019-02-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='defualt.jpg', upload_to='blog_images'),
        ),
    ]
