# Generated by Django 2.1.5 on 2019-04-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_remove_atrraction_tags'),
        ('blog', '0005_auto_20190201_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.ManyToManyField(blank=True, to='places.Place'),
        ),
    ]
